### ISSUE TITLE
صفحه اصلی 

### ISSUE THREAD

**Issue by alphapersian** [alphapersian/solar_issue#1]
> @ui_team     

![image](https://user-images.githubusercontent.com/5099477/34568602-9255bc28-f17b-11e7-8e6f-8cb96e29d903.png)
![image](https://user-images.githubusercontent.com/5099477/34568713-ede90afe-f17b-11e7-9dfd-ab35d7201d29.png)

 در عکس بالا شماره تلفن و پست الکترونیک حذف شوند و لوگو به پایین منتقل شود و در نوار سبز قرار گیرد و نواری که ای موارد داخل آن قرار دادشت به طور کلی حذف شود 
در صورت نیاز سوال فرمایین 

------------------------------------------------------------------------------------------------
> @php_team

![image](https://user-images.githubusercontent.com/5099477/34569459-1717c5da-f17e-11e7-94b9-6c3b40b7cfe4.png)
در تصویر توضیحات داده شده است 

------------------------------------------------------------------------------------------------
> @php_team

![image](https://user-images.githubusercontent.com/5099477/34569521-4b48a11c-f17e-11e7-95a5-4da1957a1d20.png)
توضیحات در تصویر مشخص شده است 
در قسمت مدیریت نوشته شده است (عنوان ) ولی وقتی وارد میکنیم تغییر صورت نمیگیرد 
در عکس پایین نمایش داده شده است 
![image](https://user-images.githubusercontent.com/5099477/34569605-8732a4a2-f17e-11e7-95ed-84d88205d845.png)

------------------------------------------------------------------------------------------------

> @php_team

> @ui_team

![image](https://user-images.githubusercontent.com/5099477/34569886-6200c014-f17f-11e7-8996-d391c8147c28.png)
  توضیحات در عکس داده شده است  - لطفا بررسی کنید که سمت چه کسی ایراد دارد و اصلاح کنید 

------------------------------------------------------------------------------------------------

> @ui_team

![image](https://user-images.githubusercontent.com/5099477/34570131-24b46b2e-f180-11e7-9c91-6b18384824d6.png)
نوشته ها باید قسمت خالی سمت چپرا گسترش دهند و نباید خالی باشد ( عرض این قسمت کافی نیست 

------------------------------------------------------------------------------------------------

> @php_team

![image](https://user-images.githubusercontent.com/5099477/34578712-3c702cec-f19b-11e7-856a-36cf44b03223.png)
توضیحات در تصویر وارد شده است 

-------------

> @php_team
![image](https://user-images.githubusercontent.com/5099477/34578958-3f3826f4-f19c-11e7-9ea7-d23f7d2fc393.png)

![image](https://user-images.githubusercontent.com/5099477/34578963-457bcf8e-f19c-11e7-98fb-3e2913bd6e75.png)

تنظیمات شبکه های اجتماعی اعمال نمیشوند 

----------------

**Comment by birzad** [comment]
عکس اسلایدر طبق طرح بود.
اسلایدر متنی نداشت تا عوض بشه
اگر یو آی جدید را بدید من هم اعمال خواهم کرد.
------------------------------------
منو ها هم لینک دارند
_________________________

**Comment by alphapersian** [comment]
![image](https://user-images.githubusercontent.com/5099477/34686270-48983b04-f4c0-11e7-87fe-52ffd5f992e7.png)


در همین طرح فعلی وجود دارد 
لطفا برای سمت مدیریت هم اعمال کنید 

----------------------------

منظور منو های پایین صفحه هستند ، لطفا لینک گذاری شود 

----------------------
 نوشته" # ویژگی های محصولات " تصویر باید قابلیت تغییر داشته باشد 

----------------------------

**Comment by birzad** [comment]
منو های پایین هم لینک دار شد.

**Comment by birzad** [comment]
عنوان اسلایدر در سمت مدیر از بخش تنظیمات صفحه اول قابل تغییر و ویرایش شد.
توجه شود که این  عنوان به ازای هر اسلاید نیست، بلکه یک عنوان کلی است برای همه اسلاید ها

**Comment by alphapersian** [comment]
>ui_team
عکس های بک گراند و فوتر باید تغییر کند 
![image](https://user-images.githubusercontent.com/5099477/34864945-d617037a-f78b-11e7-9004-ba1d798147e1.png)
 
------------
>ui_team
![image](https://user-images.githubusercontent.com/5099477/34864993-134d8bf6-f78c-11e7-9bd5-68a5dc4139c9.png)
توضیحات در عکس

----------------
>ui_team
انیمشن محصولات حذف شود زیرا در هنگام لود با  تاخیر میخورد و قبل از اسکرول لود نمیشود و این رابط کاربری را ضعیف کرده است 
 ---------------
>ui_team
لطفا بفرمایید که محصولات در این صفحه عنوان داشته اند یا نه ؟؟؟
 
---------------
>ui_team
![image](https://user-images.githubusercontent.com/5099477/34865120-c2cec68a-f78c-11e7-99b9-b17851f892a1.png)
دقت کنید برای زبان انگلسی باید پرچم را تغییر دهید 

----------
>ui_team
لایه سایه بر روی تصاویر اسلاید شو و دیگر موارد تغییر کند 

-------------
