### ISSUE TITLE
محصولات 

### ISSUE THREAD

**Issue by alphapersian** [alphapersian/solar_issue#3]
> @php_team

![image](https://user-images.githubusercontent.com/5099477/34573699-3b17a82c-f18a-11e7-95b5-efa31ac64f35.png)
  
در بخش محصولات در هر زیر محصول باید آیکن و متن محصول مطابق با همان قسمت باشد
در صورتی که فقط در یک آیتم درست است

---------

> @php_team

در تمامی صفحات  ( اینورتر - استراکچر ) پنل ها نمایش داده میشوند 

----------

**Comment by birzad** [comment]
مربوط به UI هست
شفاهی توضیح دادم

**Comment by alphapersian** [comment]
>@php_team
محصولات دسته بندی نمیگیرند و باید اصلاح شوند 
![image](https://user-images.githubusercontent.com/5099477/34877634-10019e62-f7bc-11e7-8b6d-30dbe14d9ffa.png)


----------
>@php_team
![image](https://user-images.githubusercontent.com/5099477/34877808-cfca8178-f7bc-11e7-8972-3f03b3594a80.png)
