### ISSUE TITLE
اخبار

### ISSUE THREAD

**Issue by alphapersian** [alphapersian/solar_issue#4]
> @ui_team
![image](https://user-images.githubusercontent.com/5099477/34575661-d3af675e-f190-11e7-9fe2-833c5fd58fcf.png)
 -----------

> @php_team
![image](https://user-images.githubusercontent.com/5099477/34575835-5a359bc2-f191-11e7-9777-2431e3e9813e.png)
توضیحات در  تصویر داده شده است 
 -----------------

> @php_team
![image](https://user-images.githubusercontent.com/5099477/34576013-d3508724-f191-11e7-895e-c19a5eb45387.png)
در بخش نظرات از سمت مدیریت به یک نظر ئاسخ داده شد و ثبت شد ولی در قسمت کاربری ئاسخ نمایش داده نمیشود 
تنها تغییر صورت گرفته این است که برای آخرین نظر یک علامت پاسخ نمایش داده شده 
نکته ( علامت "پاسخ " برای یک نظر غیر مربوط نمایش داده شده است ) 
مانند تصویر

![image](https://user-images.githubusercontent.com/5099477/34576108-3328ce40-f192-11e7-948c-9fefaaa5d7b1.png)

-------------------------

**Comment by birzad** [comment]
ارسال نظر درست شد.
مثبت و منفی اضافه شد.
بخش پاسخ حذفش کردم

**Comment by alphapersian** [comment]
>@php_team
قسمت مقالات در سمت مدیریت نمایش داده نمیشوند و با کلیک روی لیست مقالات به صفحه اول در مدیریت منتقل میشود 
![image](https://user-images.githubusercontent.com/5099477/34868355-c2e731be-f798-11e7-84e0-19ede0710ba9.png)
