### ISSUE TITLE
تماس با ما 

### ISSUE THREAD

**Issue by alphapersian** [alphapersian/solar_issue#5]
> @php_team
 

فرم تماس با ما کار نمیکند و چیزی برای مدیریت ارسال نمیکند 

--------------

> @php_team
نقشه صفحه تماس با ما باید حالت پویا داشته باشد و این صرفا تصویر است 
  
  --------------------

اطلاعات تماس را نمیتوان تغییر داد 
![image](https://user-images.githubusercontent.com/5099477/34579085-cf479eaa-f19c-11e7-8fe3-a8b2898f8475.png)

تغییرات اعمال نمیشوند

**Comment by birzad** [comment]
اشکال عدم ثبت اطلاعات در بخش تماس با ما رفع شد.
نقشه سایت از طریق منوی تماس با ما> تنظیمات در سمت مدیریت قابل تنظیم می باشد.
کافی است که گوگل مپ را با آدرسی که می خواهید ست کنید، و در این بخش قرار دهید.

**Comment by alphapersian** [comment]
لطفا برای نمونه یک مورد مپ را ست کنید 
تشکر

**Comment by alphapersian** [comment]
![image](https://user-images.githubusercontent.com/5099477/34686938-6e3cfdb6-f4c2-11e7-9dd1-0c1394969f32.png)
 این مورد عکس هست نه آی فریم

**Comment by alphapersian** [comment]
![image](https://user-images.githubusercontent.com/5099477/34686992-9fbbaaa4-f4c2-11e7-92e2-3f8d0fff4855.png)


![image](https://user-images.githubusercontent.com/5099477/34687008-aa40e930-f4c2-11e7-8579-03c57057faf8.png)


آقای محمدی مطمن هستن سایت آپلود شده ؟؟؟؟
