### ISSUE TITLE
درباره ما 

### ISSUE THREAD

**Issue by alphapersian** [alphapersian/solar_issue#6]
> @php_team

تغییرات درباره ما اعمال نمیشود 

--------------------------------

**Comment by birzad** [comment]
انجام شد.

**Comment by alphapersian** [comment]
همچنان اعمال نمیشود 

![image](https://user-images.githubusercontent.com/5099477/34686689-a55c2598-f4c1-11e7-8b8d-525fdb73cb9f.png)

![image](https://user-images.githubusercontent.com/5099477/34686746-c9027178-f4c1-11e7-81e2-384862f29c0d.png)

**Comment by alphapersian** [comment]
>@php_team
 در قسمت درباره ما 6 مطلب وجود دارد که فقط چهار مطلب نمایش داده میشوند 
![image](https://user-images.githubusercontent.com/5099477/34874059-b8f04812-f7ac-11e7-9bd7-2e6eabc9ed20.png)


![image](https://user-images.githubusercontent.com/5099477/34874069-c80324be-f7ac-11e7-81f4-b2560dd1c7e1.png)
